-- MySQL Script generated by MySQL Workbench
-- Tue Sep  6 09:59:11 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ecole
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ecole
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecole` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `ecole` ;

-- -----------------------------------------------------
-- Table `ecole`.`filiere`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecole`.`filiere` (
  `IDFil` INT NOT NULL AUTO_INCREMENT,
  `NomFil` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`IDFil`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecole`.`etudiant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecole`.`etudiant` (
  `IDEt` INT NOT NULL AUTO_INCREMENT,
  `NomEtudiant` VARCHAR(25) NOT NULL,
  `PrenomEtudian` VARCHAR(25) NULL DEFAULT NULL,
  `DateNaissance` DATE NULL DEFAULT NULL,
  `Ville` VARCHAR(25) NULL DEFAULT NULL,
  `IDFil` INT NULL DEFAULT NULL,
  PRIMARY KEY (`IDEt`),
  INDEX `IDFil_idx` (`IDFil` ASC) VISIBLE,
  CONSTRAINT `IDFil`
    FOREIGN KEY (`IDFil`)
    REFERENCES `ecole`.`filiere` (`IDFil`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
